### ISSUE TITLE
Menampilkan nomor penting saat terjadi bencana

### ISSUE THREAD

**Issue by affand20** [affand20/Gapana#11]
## Scenario

- User bisa mendapatkan informasi nomor-nomor penting yang dapat dihubungi saat terjadi bencana seperti SAR, Polisi, dll.
- Terdapat tombol yang bisa dipencet user untuk mengakses informasi nomor-nomor penting tersebut

### Task

- [x] Tampilkan tombol untuk memunculkan dialog(popup) yang berisi nomor-nomor penting
- [x] Ketika tombol ditekan seharusnya memunculkan popup yang berisi nomor" penting

**Comment by novianagta** [comment]
Menampilkan tombol nomor penting

**Comment by affand20** [comment]
selesai dengan a649d66 dan 23bfe42
