### ISSUE TITLE
Panduan penggunaan Aplikasi

### ISSUE THREAD

**Issue by affand20** [affand20/Gapana#14]
## Scenario

- User bisa membaca panduan penggunaan ketika bingung saat menjalankan aplikasi
- Menu panduan diakses dari #13 

### Task
- [x] Sediakan halaman yang berisi panduan dari aplikasi

**Comment by affand20** [comment]
#13

**Comment by tinezaisyah** [comment]
tampilan panduan berupa Q&A di web

**Comment by tinezaisyah** [comment]
url panduan : https://sites.google.com/view/panduangapana

**Comment by affand20** [comment]
topp wis 👍 👍
