### ISSUE TITLE
Tentang Aplikasi

### ISSUE THREAD

**Issue by affand20** [affand20/Gapana#15]
## Scenario

- User dapat mengetahui tentang aplikasi seperti versi, pembuat, tanggal dibuat, dll.

### Task

- [ ] Sediakan halaman untuk informasi tentang aplikasi

**Comment by Aldinoharyop** [comment]
Sudah selesai dibuat menunya, hanya saja kalimat tentang aplikasi bisa diperbaharui.

**Comment by Aldinoharyop** [comment]
Sudah Selesai .
