### ISSUE TITLE
menampilkan  video dalam edukasi pasca

### ISSUE THREAD

**Issue by muhyiddin878** [affand20/Gapana#19]
## Scenario 
1. user dapat melihat video healing melalui youtube dengan link
2. user dapat memilih berbagai macam video healing yang tersedia 

### Task

- [ ] link dapat langsung dialihkan ke youtube

- [ ] list video muncul semua

**Comment by glryac** [comment]
link video trauma healing :
https://www.youtube.com/watch?v=Zv8bg35U36w
https://www.youtube.com/watch?v=ML-QusthTIw
https://www.youtube.com/watch?v=Teg_kgDFMQ8

**Comment by hudadewantoro** [comment]
https://youtu.be/OUlQ37EPDc8
https://youtu.be/lcE-wlxte4k
https://youtu.be/Teg_kgDFMQ8
