### ISSUE TITLE
Mmebuat Web Admin Edukasi Pasca Bencana

### ISSUE THREAD

**Issue by muhyiddin878** [affand20/Gapana#20]
related with #19 

## Scenario
1. admin dapat memposting link video untuk healing melalui web
2. admin dapat memodifikasi list link video yang ada di video healing 

### Task

- [x] link dapat di masukkan melalui web admin

- [x] link di web admin sama dengan yang ditampilkan di video healing

**Comment by glryac** [comment]
link video trauma healing :
https://www.youtube.com/watch?v=Zv8bg35U36w
https://www.youtube.com/watch?v=ML-QusthTIw
https://www.youtube.com/watch?v=Teg_kgDFMQ8

**Comment by affand20** [comment]
overall fitur sudah selesai, tinggal upload ke web hosting
