### ISSUE TITLE
DB Nomor penting

### ISSUE THREAD

**Issue by tinezaisyah** [affand20/Gapana#22]
Database nomor penting yang digunakan untuk meminta bantuan

**Comment by affand20** [comment]
edit disini gaes [spreadsheet](https://docs.google.com/spreadsheets/d/1mCNxGXM6b1KFC_FkAypLwLNeHkSsHAQljvYaS335WoM/edit?usp=sharing)

**Comment by emirrifqy** [comment]
Udah aku isi yaa

**Comment by akhwanmaujuddin** [comment]
Udah tak tambah buat  daerah bali, yogya, bandung, malang
